
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
#   api_password: eid1eitohpiS

#reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

#database:
#  path: /config/frigate.db

recorder:
  db_url: sqlite:////data/home-assistant_v2
  commit_interval: 60

homeassistant:
# Name of the location where Home Assistant is running
  name: Reimers Home Assistant Instance
  # Location required to calculate the time the sun rises and sets
  latitude: 53.605782
  longitude: 10.045693
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 20
  country: DE
  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml

automation: !include automations.yaml
logger: !include logger.yaml
media_player: !include devices/player.yaml
mqtt: !include_dir_merge_named mqtt/
#mqtt: !include mqtt/mqtt.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


template: !include templates.yaml
